# Generated by Django 3.2.25 on 2026-01-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendancesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceSummary',
        ),
    ]
