# Generated by Django 3.2.25 on 2026-01-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_attendancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use first day of the month (e.g. 2026-01-01)')),
                ('total_days', models.PositiveIntegerField()),
                ('present_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
