# Generated by Django 3.2.25 on 2026-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_monthlyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_class',
            field=models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=10),
        ),
    ]
